### PR TITLE
fix warmstart, allow Biot-Savart linearization, fix induction residual bug

### PR DESCRIPTION
**Pull request by rcleuthold**

### CODE REVIEW

**Comment by rcleuthold** [comment]
I haven't actually gotten the memory problem fixed, but I did find/repair a bug in the induction model residuals. So, I'd like to merge/pull this update asap. All tests run, and no pdb statements remaining!
All the best, rachel

**Comment by rcleuthold** [comment]
oops.

**Comment by thilobro** [comment]
Looks good to me. Is it ready to merge? @rcleuthold

**Comment by rcleuthold** [comment]
yes :)

**Comment by rcleuthold** [comment]
thank you!

**Pull request merged**
