### PR TITLE
Feature/plot var bounds

### PR DESCRIPTION
**Pull request by jdeschut**
Plot variable bounds in any of these plots:

```
trial.plot(['states', 'controls','algebraic_variables', 'lifted_variables'])
```

Switch on/off with:

```
options['visualization']['cosmetics']['plot_bounds'] = True
```

It ends up looking like this:

variable_bounds_plot

Should we make it the default option? Sometimes the trajectory is so far off the bounds, that the plot becomes useless (see e.g. the plot for `l_t`)

### CODE REVIEW

**Comment by thilobro** [comment]
I would not make it default due to scaling reasons

**Review by rcleuthold — COMMENTED** [review]
Very useful! Thanks!

**Comment by rcleuthold** [comment]
I don't know if I actually have "write access". If you want me to merge the pull request, I might need to be added! :)

**Comment by jdeschut** [comment]
> I don't know if I actually have "write access". If you want me to merge the pull request, I might need to be added! :)

Fixed!

**Comment by rcleuthold** [comment]
thanks!

**Comment by jdeschut** [comment]
> Very useful! Thanks!

What do you think about default/non-default? I'm currently tending towards default because it gives you an immediate overview of all the bounds. Even if you don't see the details of the tether reel-out profile, because on the other hand, you can more easily spot the tether range.

**Pull request merged**
