### PR TITLE
Feature/debug logger

### PR DESCRIPTION
**Pull request by thilobro**
### Overhaul of our logging architecture
* Before: loglevels and formatting was set globally in the experiment scripts. This has two flaws:
  * code replicated in every experiment
  * global logging config also used by included modules, e.g. matplotlib

* now: `Logger` class in `awebox/logger/logger.py` handles logging
  * set loglevel for console/file in `awebox/logger/logging.conf`
  * in order to use logger, do `from awebox.logger.logger import Logger as awelogger; awelogger.logger.info('TEST)`

Also fixed bug that made 3D plots crash

### CODE REVIEW

**Comment by thilobro** [comment]
all tests run through. If we merge this however, you will have to update your personal experimental files accordingly (by removing the logger config there)

**Comment by rcleuthold** [comment]
what is the new procedure for getting verbose IPOPT outputs? 
logging.conf seems to imply that we only have two output levels: "INFO" and "WARNING" 
is this true? what happened to DEBUG?

**Comment by jdeschut** [comment]
To customize logging the idea is that you copy the default `logging.conf` to your experimental folder. `awebox` will detect it and override the default one. You can then change the settings in your personal config file to DEBUG.

**Comment by thilobro** [comment]
By setting the awebox log level, the IPOPT print level can only toggled between the default (5, if I remember correctly) and 0 (no output besides the disclaimer). This is handled here:
https://github.com/awebox/awebox/blob/develop/awebox/opti/preparation.py#L217
If you want to directly control IPOPT's print level, you would need to implement that functionality there (should also be easy enough to hack, although of course we don't do that sort of thing...)

PS: the consoleHandler's level handles what is printed into the console, the fileHandler handles what is logged in log file (if nothing is there to log, no file is created)

**Comment by rcleuthold** [comment]
figured it out! thanks... 

```
from awebox.logger.logger import Logger as awelogger
awelogger.logger.setLevel(10)
```

**Pull request merged**
