### PR TITLE
Iteration on constraints formulation

### LINKED ISSUE #46: Restore sparsity pattern in parallelized constraint evaluation case

### PR DESCRIPTION
**Pull request by jdeschut**
Restore some of the functionality that was lost in #45 :

- [x] create `casadi.struct_symSX` object of constraints for a posteriori debugging
- [x] desired sparsity pattern for constraints construction with `casadi.map` (remove "serial" implementation, closes #46 )
- [x] lifting of algebraic/lifted and state derivative values on shooting nodes for multiple shooting and legendre collocation

Improve current formulation:

- [x] also lift algebraic/lifted and state derivative values on shooting nodes for radau collocation

Some technical details:

- No more variable bounds on collocation nodes in all possible formulations --> they are treated as integration variables purely
- New structure of `V`:

   ```python
   > trial.optimization.V_opt.keys()                                                        
   ['theta', 'phi', 'xi', 'xd', 'u', 'xddot', 'xa', 'xl', 'coll_var']
   ```
   Notice that `xddot` needs to be lifted always since the `ddq{}{}` variables enter the algebraic tether constraints.
- New structure of `g`:

   ```python
   > trial.nlp.g_struct.keys()                                                              
   ['dynamics', 'algebraic', 'path', 'collocation', 'continuity', 'periodic']
   ```
   where the `dynamics` and `algebraic` entries are new, to determine the lifted `xddot` and `xa`/`xl` variables.

### CODE REVIEW

**Comment by jdeschut** [comment]
Sparsity pattern of `single_kite_lift_mode` example, and close-up at the end of the trajectory.
g_sparsity
g_sparsity_close_up

**Comment by jdeschut** [comment]
```bash
> pytest test_trials.py::test_vortex_trial
```
does not run due to 4 missing constraints in `model.dynamics`. Will be fixed in new PR.

Otherwise test run trough, ready for review @rcleuthold .

**Comment by jdeschut** [comment]
@rcleuthold any chance for a review?

**Comment by rcleuthold** [comment]
sorry - i completely spaced on this.
but, i'm sure that it's good. :)

**Pull request merged**
