### PR TITLE
Classical continuation

### PR DESCRIPTION
**Pull request by jdeschut**
- allow user to apply "classical continuation" as well as "penalty-based homotopy" (default):
  ```
  options['solver']['homotopy_method'] = 'penalty' / 'classic'
  options['solver']['homotopy_step'] = 0.1 # for 'classic' case
  ```
- record `t_wall` in `optimization` (otherwise optimization timings include e.g. callback timings etc..).
- some callback clean-up and fixes.
- fix `single_kite_lift_mode` example (is not running on develop after tether kinetic energy fix)

### CODE REVIEW

**Comment by jdeschut** [comment]
Test still running.

**Comment by jdeschut** [comment]
Tests run through :+1:

**Comment by rcleuthold** [comment]
Hi Joshi,
I really don't mean to slow down your work - if you think that this is
necessary for your paper(s) - but, I don't think that classical
continuation is going to be useful to our users, and I think that we should
be attempting to avoid
"growing-the-code-that-needs-to-be-maintained-in-unnecessary-ways." is it
possible to  keep an eye out to limit unnecessary feature creep while doing
your expansion?
(said with a helpful, and forwards-looking tone, and attempting not to
sound passive aggressive...)
All the best,
Rachel

**Comment by jdeschut** [comment]
Hi Rachel! I agree that feature creep is undesired and that our code is prone to it. I also think it will not be very useful for AWE practitioners since it rarely outperforms the penalty-based approach (or converges when the penalty-based method does not, though it does happen). Here is my motivation of why I would include this feature nevertheless:

- I'd like to open-source my benchmarking code (penalty vs. classic) so that reviewers or other interested parties can reproduce the results.
- maintenance cost is very limited as it's implemented in all in all just twenty lines of code.

Let me know what you think!

**Comment by rcleuthold** [comment]
Hi Joshi,
I definitely don't think that *I* can tell you what you should/should-not
implement, because you know best what you need for your research. (Same
holds for me! ;) )
My comment is more general: that all of us should try to be careful about
evaluating what expansions are useful, and what are not.
All the best/happy coding,
Rachel

**Comment by jdeschut** [comment]
Great! But what does that mean for the review/merge? :smile:

**Comment by rcleuthold** [comment]
sorry, isn't it a WIP?

**Comment by jdeschut** [comment]
Nope, all ready! (Same for #69)

**Pull request merged**
