### PR TITLE
Tether attachment options

### PR DESCRIPTION
**Pull request by jdeschut**
This feature implements the possibility to fix tethers at different locations than the center-of-mass ("com") of kites.

```python
options['model']['tether']['attachment'] = 'com' / 'stick'
options['model']['tether']['cross_tether']['attachment'] = 'com'/'stick'/'wing_tip'
```

The `stick` tether attachment point is given as 3D-vector in the body frame in 
```python
options['model']['geometry']['overwrite']['r_tether']
```

In the case of `wing_tip` cross-tether attachment, rotation constraints to avoid collision with cross-tether are removed.

Currently, all non-`com`-options are supported for 6DOF kites only.

Following changes to the code are implemented:
- [x] adjust holonomic constraints and time-derivatives for main/secondary tethers.
- [x] adjust holonomic constraints and time-derivatives for cross-tethers.
- [x] add extra moment contribution to rotational dynamics.
- [x] adjust initialization for correct cross-tether length and kite orientation in `wing_tip`-case
- [x] re-implement rotation constraints (including one for the `wing_tip`-case)
- [x] adjust initialization for feasible trajectories in `wing_tip`-case

To do later:
- assess assumption of rotation inequalities that tether and stick are always more or less aligned.
- adjust initialization for feasible trajectories in `stick`-case

### CODE REVIEW

**Comment by jdeschut** [comment]
Tests run through.

**Comment by thilobro** [comment]
Looks good! Some small remarks:
* in the holonomic constraints formulation, you duplicate some code for the derivatives. Maybe one can abstract that to a function?
* I think it makes sense to reformulate the span inequality as
`cos(span_angle) - R1.T q / norm(q)`
so that it scales a bit nicer

**Comment by jdeschut** [comment]
- you're right there is some duplicate code there, I'll make a function for it.
- I intentionally wrote the span inequality constraint as
```
cos(span_angle)* norm(q) - R1.T * q
```
since this makes the constraint (derivatives) less nonlinear.
But we can divide the entire expression by the cross-tether natural length to make it dimensionless.

**Comment by thilobro** [comment]
sounds good to me

**Comment by jdeschut** [comment]
Can be merged.

**Pull request merged**
